{
 "title": "Application Telemetry (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Chain Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OVL Mint Increase Rate",
   "type": "timeseries",
   "description": "This is how quickly the ovl_token_minted metric is increasing over short time intervals, which can help you identify sudden spikes or changes in the minting activity.",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 1 },
   "targets": [
    { "expr": "irate(ovl_token_minted[1m])" }
   ]
  },
  {
   "title": "Number of OVL tokens minted",
   "type": "graph",
   "description": "Number of OVL tokens minted",
   "gridPos": { "h": 15, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ovl_token_minted" }
   ]
  },
  {
   "title": "Unrealised profit and loss",
   "type": "graph",
   "description": "Unrealised profit and loss",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upnl" }
   ]
  },
  {
   "title": "Collateral",
   "type": "graph",
   "description": "Collateral",
   "gridPos": { "h": 15, "w": 10, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collateral_rem" }
   ]
  },
  {
   "title": "Unrealised profit and loss (Percentage)",
   "type": "graph",
   "description": "Unrealised profit and loss (Percentage)",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upnl_pct" }
   ]
  }
 ]
}