global:
  scrape_interval:     5s
  evaluation_interval: 30s

scrape_configs:
- job_name: my-application
  honor_labels: true
  metrics_path: /
  static_configs:
  - targets: ['chain-monitoring:8000']
# - job_name: siwa-monitoring
#   honor_labels: true
#   metrics_path: /metrics
#   static_configs:
#   - targets: ['docker.for.mac.localhost:81']

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - 'alertmanager:9093'  # Replace with your Alertmanager address

# rule_files:
#   - 'your_alert_rules.yml'

# remote_write:
#   - url: 'https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push'
#     basic_auth:
#       username: 1264667
#       password: glc_eyJvIjoiOTc5NTUxIiwibiI6InN0YWNrLTc3ODM4My1pbnRlZ3JhdGlvbi1vdmVybGF5LXByb21ldGhldXMiLCJrIjoiODcyWTQzRWQyQ3g0SVdzZGgzMzBscHdjIiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=
